### PR TITLE
ClientServerChannel log enhancement

### PR DESCRIPTION
**Pull request by fhilg**
## Description
- ClientServerChannel logging enhancement copied from ns-3 federate:
  - less verbose by default
  - log level configurable
- some macros and functions were copied from ns-3.34:
  - log macros copied and some modified
  - ParameterLogger copied and slightly modified

## Related Issue
- internal issue 200

### CODE REVIEW

**Comment by fhilg** [comment]
Communication logs of scenario `AdhocCommunication` with MOSAIC's debug level set to "debug" or "info":
- [200 OPP DEBUG.zip](https://github.com/mosaic-addons/omnetpp-federate/files/6976640/200.OPP.DEBUG.zip)
- [200 OPP INFO.zip](https://github.com/mosaic-addons/omnetpp-federate/files/6976642/200.OPP.INFO.zip)

Federate debug levels are not changed.

**Comment by kschrab** [comment]
> Communication logs of scenario `AdhocCommunication` with MOSAIC's debug level set to "debug" or "info":
> 
> * [200 OPP DEBUG.zip](https://github.com/mosaic-addons/omnetpp-federate/files/6976640/200.OPP.DEBUG.zip)
> * [200 OPP INFO.zip](https://github.com/mosaic-addons/omnetpp-federate/files/6976642/200.OPP.INFO.zip)
> 
> Federate debug levels are not changed.

It would be more interessting to see outputs of different Federate log levels. IMO the CommunicationDetails.log is still too verbose. The simulation of one single message results in a log output of 60 lines! This should be reduced by increasing log-levels in our federate for the actual outputs, and by reviewing the default log-configuration for the federate (where can we configure this actually?).

**Comment by fhilg** [comment]
I added a configuration option to `omnetpp.ini` setting the log level of `ClientServerChannel`, as discussed.

Excerpt of `omnetpp.ini`:
```
# ClientServerChannel
# -------------------
# OMNeT++ log level names are valid, same hierarchy is used
clientserverchannel-log-level = trace
```

The following archive contains the `CommunicationDetails.log` of scenario `AdhocCommunication` with different log levels of `ClientServerChannel` set:
[200 OPP LOG ClientServerChannel.zip](https://github.com/mosaic-addons/omnetpp-federate/files/6999604/200.OPP.LOG.ClientServerChannel.zip)

**Comment by kschrab** [comment]
> I added a configuration option to `omnetpp.ini` setting the log level of `ClientServerChannel`, as discussed.
> 
> Excerpt of `omnetpp.ini`:
> 
> ```
> # ClientServerChannel
> # -------------------
> # OMNeT++ log level names are valid, same hierarchy is used
> clientserverchannel-log-level = trace
> ```
> 
> The following archive contains the `CommunicationDetails.log` of scenario `AdhocCommunication` with different log levels of `ClientServerChannel` set:
> [200 OPP LOG ClientServerChannel.zip](https://github.com/mosaic-addons/omnetpp-federate/files/6999604/200.OPP.LOG.ClientServerChannel.zip)

1. Why is ClientServerChannel logging on error stream?
  > 2021-08-17 13:31:00,284 ERROR OmnetppError - Process Omnetpp : ClientServerChannel: read config message time: 0
2. Refering to my previous comment, this is not only about the CientServerChannel.. the whole federate log needs to be revised, this is still way too verbose. There are 21k lines of log whereas the TRACE log of SNS has only 2000 lines..  In the INFO log we really only need basic information about what nodes are configured and may be 2 or 3 lines for each message being sent. What can we configure here?

**Comment by fhilg** [comment]
I recreated the `CommunicationDetails.log` with the following federate configuration:
```
...
mosaiceventscheduler-debug = false
...
clientserverchannel-log-level = warn
...
*.mgmt.debug = false
...
**.cmdenv-log-level = info
...
**.wlan*.radio.receiver.sensitivity = -81.0dBm
...
```
The branch [fhilg:199-sns-logging](https://github.com/eclipse/mosaic/pull/138) of MOSAIC is used.

### Log

- [CommunicationDetails.zip](https://github.com/mosaic-addons/omnetpp-federate/files/7186795/CommunicationDetails.zip)
- [extract.txt](https://github.com/mosaic-addons/omnetpp-federate/files/7186796/extract.txt)

### Quick Analysis

Occurances | Search Expression
-- | --
1439 | Changing radio reception state from
1436 | bpsk snr=
1392 | Changing radio transmission state from
1275 | Reception ended:
1275 | Reception started:
1044 | Frame
952 | handleMessage()
741 | Radio mode changed from
707 | Received (inet::Packet)
707 | Setting NAV to
707 | The radio channel has become free
359 | Broadcast received
359 | Delivering
359 | MosaicUDP received packet:
359 | Packet .* received from network
359 | Passing up to protocol
359 | Received frame from PHY:
359 | Sending payload up to socket
359 | Sending up (inet::Packet)
353 | MosaicScenarioManager
353 | Socket created:
348 | backoffslots =
348 | Channel granted:
348 | Frame omnetpp_federate::MosaicAppPacket
348 | lastBusyTime =
348 | Processing upper frame:
348 | The upper frame has been classified
348 | Transmission ended:
348 | Transmission started:
348 | waitInterval =
60 | Initialize MosaicMobility
15 | Changing radio channel
5 | Initializing MosaicUDPApp
5 | Setting channel


Occurances | Search Expression
-- | --
18122 | Messages searched for
3560 | other messages
21682 | Total Messages

### Suggestion

There are 348 messages sent which lead to several log records each. A reduction to one record per message send event would result in reduction by at least 2784 log entries for sending. The same applies to reception.

The following log entries are better suited for more detailed log levels:
```
...
2021-09-17 16:37:30,844 INFO  OmnetppOutput - Process Omnetpp : 7.021423655: Changing radio reception state from [1mIDLE[0m to [1mUNDEFINED[0m.
2021-09-17 16:37:30,844 INFO  OmnetppOutput - Process Omnetpp : 7.021423655: Changing radio transmission state from [1mUNDEFINED[0m to [1mIDLE[0m.
...
2021-09-17 16:37:30,847 INFO  OmnetppOutput - Process Omnetpp : 7.022159903: bpsk snr=14782.3 ber=0
...
2021-09-17 16:37:30,844 INFO  OmnetppOutput - Process Omnetpp : 7.021423655: Frame omnetpp_federate::MosaicAppPacket has been inserted into the PendingQueue.
...
2021-09-17 16:37:30,847 INFO  OmnetppOutput - Process Omnetpp : 7.022159655: Frame sequence finished
...
```

#### Log entry reduction @INFO (estimation)

Amount | Log Message
-- | --
2784 | Sending
5000 | Receiving
5300 | state change, "`bpsk snr=`"
```

**Comment by fhilg** [comment]
#### Possible Next Steps
- find corresponding _INET_ modules
- configure log levels for each module
  - Example (_radio_ and _mac_ at level _warn_, rest at level _info_): [CommunicationDetails.zip](https://github.com/mosaic-addons/omnetpp-federate/files/7187393/CommunicationDetails.zip)
    ```
    **.radio.cmdenv-log-level = warn
    **.mac.**.cmdenv-log-level = warn
    **.cmdenv-log-level = info
    ```

**Comment by fhilg** [comment]
### Setting All Log Levels To WARN

By default log level should be set to WARN. The log level of modules of interest can be set to INFO:

```
# modules of interest
...
**.udp.cmdenv-log-level = info
...

# default log level
**.cmdenv-log-level = warn
```

As discussed in the internal meeting I created a listing of all INET modules:
[all INET modules set to INFO.txt](https://github.com/mosaic-addons/omnetpp-federate/files/7203644/all.INET.modules.txt)

Having had a quick look into that list, I removed some modules which do not generate any log message: 
[some INET modules set to INFO.txt](https://github.com/mosaic-addons/omnetpp-federate/files/7203679/INET.modules.-.reduced.txt)

**Comment by fhilg** [comment]
## DEBUG / INFO Logs of Scenario _AdhocCommunication_
### Configurations
The following federate configurations are used for DEBUG and INFO levels. Keep in mind: ns-3 log levels are defined differently:

MOSAIC / OMNeT++ level | equivalent ns-3 level
--- | ---
TRACE | LOGIC
DEBUG or DETAIL | INFO or FUNCTION
INFO | DEBUG
WARN | WARN

#### DEBUG: ns-3 federate
```
     <component name="MosaicStarter" value="warn|error|debug|info"/>
     <component name="MosaicSimulatorImpl" value="warn|error|debug|info"/>
     <component name="MosaicNs3Server" value="warn|error|debug|info"/>
     <component name="MosaicNodeManager" value="warn|error|debug|info"/>
     <component name="MosaicProxyApp" value="warn|error|debug|info|function|func"/>
     <component name="ClientServerChannel" value="warn|error"/>
     
     <component name="UdpSocketImpl" value="warn|error|info"/>
     <component name="UdpL4Protocol" value="warn|error|info"/>
     <component name="Ipv4L3Protocol" value="warn|error|info"/>
     <component name="Ipv4Interface" value="warn|error|info"/>
     <component name="TrafficControlLayer" value="warn|error|info"/>
     
     <component name="PropagationLossModel" value="warn|error|info"/>
     <component name="WifiPhy" value="warn|error|info|function"/>
     <component name="YansWifiPhy" value="warn|error|info"/>
     <component name="WaveNetDevice" value="warn|error|info"/>
     <component name="YansWifiChannel" value="warn|error|info"/>
     <component name="InterferenceHelper" value="warn|error|info"/>
```

#### INFO: ns-3 federate
```
     <component name="MosaicStarter" value="warn|error|debug|info"/>
     <component name="MosaicSimulatorImpl" value="warn|error|debug"/>
     <component name="MosaicNs3Server" value="warn|error"/>
     <component name="MosaicNodeManager" value="warn|error|debug"/>
     <component name="MosaicProxyApp" value="warn|error|debug|func"/>
     <component name="ClientServerChannel" value="warn|error"/>
     
     <component name="UdpSocketImpl" value="warn|error"/>
     <component name="UdpL4Protocol" value="warn|error"/>
     <component name="Ipv4L3Protocol" value="warn|error"/>
     <component name="Ipv4Interface" value="warn|error"/>
     <component name="TrafficControlLayer" value="warn|error"/>
     
     <component name="PropagationLossModel" value="warn|error"/>
     <component name="WifiPhy" value="warn|error"/>
     <component name="YansWifiPhy" value="warn|error"/>
     <component name="WaveNetDevice" value="warn|error"/>
     <component name="YansWifiChannel" value="warn|error"/>
     <component name="InterferenceHelper" value="warn|error"/>
```

#### DEBUG: OMNeT++ federate
This is a very verbose configuration and therefore considered as log level "DEBUG".
```
**.cmdenv-log-level = info
```

#### INFO: OMNeT++ federate
This configuration comes close to _"1-2 log entries per message transmission"_.
```
**.rx.cmdenv-log-level = info
**.cmdenv-log-level = warn
```

### Log Result
[complete logs.zip](https://github.com/mosaic-addons/omnetpp-federate/files/7225681/complete.logs.zip)

**Comment by fhilg** [comment]
As discussed I changed the logging and generated the 6 logs again (MOSAIC branch 199, this OMNeT++ federate branch).

## Log Configurations
### INFO
#### ns-3 Federate
```
<component name="*" value="prefix_level|prefix_time"/>

<component name="MosaicStarter" value="warn|error|debug|info"/>
<component name="MosaicSimulatorImpl" value="warn|error|debug|info"/>
<component name="MosaicNs3Server" value="warn|error"/>
<component name="MosaicNodeManager" value="warn|error|debug"/>
<component name="MosaicProxyApp" value="warn|error|debug|func|info"/>
<component name="ClientServerChannel" value="warn|error"/>

<component name="UdpSocketImpl" value="warn|error"/>
<component name="UdpL4Protocol" value="warn|error"/>
<component name="Ipv4L3Protocol" value="warn|error"/>
<component name="Ipv4Interface" value="warn|error"/>
<component name="TrafficControlLayer" value="warn|error"/>

<component name="PropagationLossModel" value="warn|error"/>
<component name="WifiPhy" value="warn|error"/>
<component name="YansWifiPhy" value="warn|error"/>
<component name="WaveNetDevice" value="warn|error"/>
<component name="YansWifiChannel" value="warn|error"/>
<component name="InterferenceHelper" value="warn|error"/>
```

#### OMNeT++ Federate
```
cmdenv-log-prefix = "%t: [%M] "

**.tx.cmdenv-log-level = info
**.rx.cmdenv-log-level = info
**.proxyApp.cmdenv-log-level = info
Simulation.mgmt.cmdenv-log-level = info

**.cmdenv-log-level = warn
```

### DEBUG
#### ns-3 Federate
```
<component name="*" value="prefix_level|prefix_time"/>

<component name="MosaicStarter" value="warn|error|debug|info"/>
<component name="MosaicSimulatorImpl" value="warn|error|debug|info"/>
<component name="MosaicNs3Server" value="warn|error"/>
<component name="MosaicNodeManager" value="warn|error|debug"/>
<component name="MosaicProxyApp" value="warn|error|debug|func|info"/>
<component name="ClientServerChannel" value="warn|error"/>

<component name="UdpSocketImpl" value="warn|error|debug"/>
<component name="UdpL4Protocol" value="warn|error|debug"/>
<component name="Ipv4L3Protocol" value="warn|error|debug"/>
<component name="Ipv4Interface" value="warn|error|debug"/>
<component name="TrafficControlLayer" value="warn|error|debug"/>

<component name="PropagationLossModel" value="warn|error|debug"/>
<component name="WifiPhy" value="warn|error|debug"/>
<component name="YansWifiPhy" value="warn|error|debug"/>
<component name="WaveNetDevice" value="warn|error|debug"/>
<component name="YansWifiChannel" value="warn|error|debug"/>
<component name="InterferenceHelper" value="warn|error|debug"/>
```

#### OMNeT++ Federate
```
cmdenv-log-prefix = "%t: [%M] "

**.cmdenv-log-level = info
```

## Resulting Log
[complete logs.zip](https://github.com/mosaic-addons/omnetpp-federate/files/7245572/complete.logs.zip)

**Comment by fhilg** [comment]
- As discussed I changed the logging and generated the 6 logs again (MOSAIC branch 199, this OMNeT++ federate branch, ns-3 federate branch [log-to-std-out](https://github.com/fhilg/ns3-federate/tree/log-to-std-out))
- same configuration as above

[complete logs.zip](https://github.com/mosaic-addons/omnetpp-federate/files/7267876/complete.logs.zip)
.

**Comment by fhilg** [comment]
- As discussed I changed the logging and generated the 6 logs again (MOSAIC branch 199, this OMNeT++ federate branch, ns-3 federate branch log-to-std-out (same as branch main))
- same configuration as above
- [complete logs.zip](https://github.com/mosaic-addons/omnetpp-federate/files/7284703/complete.logs.zip)

**Pull request merged**
